# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-workflow-simple-workflow
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-cloud-workflow-simple
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-cloud-workflows.git
      sourceType: git
      dir: /modules/simple_workflow
    version: 0.1.3
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: gcs_event_arc_trigger_workflow
        location: examples/gcs_event_arc_trigger_workflow
      - name: pubsub_event_arc_trigger_workflow
        location: examples/pubsub_event_arc_trigger_workflow
      - name: schedule_workflow
        location: examples/schedule_workflow
      - name: schedule_workflow_autocreate_sa
        location: examples/schedule_workflow_autocreate_sa
      - name: schedule_workflow_with_arguments
        location: examples/schedule_workflow_with_arguments
      - name: simple_workflow
        location: examples/simple_workflow
  interfaces:
    variables:
      - name: project_id
        description: The project ID to deploy to
        varType: string
        required: true
      - name: workflow_name
        description: The name of the cloud workflow to create
        varType: string
        required: true
      - name: workflow_description
        description: Description for the cloud workflow
        varType: string
        defaultValue: ""
      - name: location
        description: The name of the location where workflow will be created
        varType: string
        required: true
      - name: workflow_source
        description: Workflow YAML code to be executed. The size limit is 32KB.
        varType: string
        required: true
      - name: workflow_labels
        description: A set of key/value label pairs to assign to the workflow
        varType: map(string)
        defaultValue: {}
      - name: service_account_email
        description: Service account email.
        varType: string
        connections:
          - source:
              source: github.com/terraform-google-modules/terraform-google-service-accounts//modules/simple-sa
              version: ">= 4.4"
            spec:
              outputExpr: email
    outputs:
      - name: revision_id
        description: The revision of the workflow. A new one is generated if the service account or source contents is changed.
      - name: workflow_id
        description: Workflow identifier for the resource with format projects/{{project}}/locations/{{region}}/workflows/{{name}}
        type: string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/workflows.admin
          - roles/workflows.invoker
    services:
      - iam.googleapis.com
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
      - workflows.googleapis.com
      - logging.googleapis.com
      - storage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.53, < 7"
